name: pryor_packages
version: 0.1.0
publish_to: none
description: "Monorepo for Pryor's Dart packages"
sdkPath: .fvm/flutter_sdk
environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  melos: ^6.3.3
