name: calendar_date
description: "A Dart package for managing timezone-agnostic calendar dates."
version: 0.9.0
homepage: https://github.com/davidpryor/calendar_date

environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
