name: strider
description: "A Dart package for creating Swift-like Strides."
version: 0.9.0
homepage: https://github.com/davidpryor/calendar_date/tree/master/packages/strider

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
